### ISSUE TITLE
improve rewarder functionality

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-discord-cli#2]
Currently one can add / remove top up reminders for rewarders and list all tracked rewarders.

Seems like the top up reminder is not working reliably, was not triggered for empty deus rewarder. Was working with hundred rewarder which is empty now (maybe empty rewarders are an issue)

Also would be nice if the `rewarder_list_tracked` would print out the reward token & maybe the assigned masterchef pool Id

**Comment by franzns** [comment]
done
